CREATE DATABASE SALES
ON PRIMARY
(
	NAME = SALES_DATA,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\Data\Sales_DATA.mdf',
	SIZE = 10MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 10%
)
LOG ON
(
	NAME = SALES_LOG,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\Data\Sales_log.ldf',
	SIZE = 10MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 10%
)
USE SALES
GO
CREATE TYPE ID FROM CHAR(8);

CREATE TABLE KHACH_HANG
(
	MA_KH ID NOT NULL,
	TEN_KH NVARCHAR(50),
	NGAYSINH DATE,
	DIACHI NVARCHAR(100),
	SODIENTHOAI VARCHAR(15),
	EMAIL VARCHAR(50),
	TAIKHOAN CHAR(8),
	MA_GIANHANG ID NULL,
	MA_GIOHANG ID
	CONSTRAINT PK_KH PRIMARY KEY(MA_KH),
	CONSTRAINT UNQ_SODIENTHOAI UNIQUE(SODIENTHOAI)
) 

CREATE TABLE GIAN_HANG
(
	MA_GH ID NOT NULL,
	SODIENTHOAI VARCHAR(15),
	EMAIL VARCHAR(50),
	NGAYLAP DATETIME,
	DANHGIA INT CHECK (DANHGIA BETWEEN 1 AND 5),
	CONSTRAINT PK_GH PRIMARY KEY (MA_GH),
	CONSTRAINT UNQ_SODIENTHOAIGH UNIQUE(SODIENTHOAI)
)

CREATE TABLE TAIKHOAN
(
	TAIKHOAN CHAR(8) NOT NULL,
	MATKHAU	CHAR(8) NOT NULL CHECK (LEN(MATKHAU) BETWEEN 6 AND 8),
	NGAYKHOITAO DATETIME DEFAULT GETDATE(),
	TINHTRANGKICHHOAT BIT DEFAULT 1,
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY (TAIKHOAN)
)

CREATE TABLE GIOHANG
(
	MA_GH ID NOT NULL,
	TONGTIEN MONEY,
	CONSTRAINT PK_GIOHANG PRIMARY KEY (MA_GH)
)

CREATE TABLE GIOHANG_CHITIET
(
	MA_GH ID,
	MA_SP ID,
	SL INT,
	DONGIA MONEY
	CONSTRAINT PK_GHCT PRIMARY KEY (MA_GH, MA_SP)
)

CREATE TABLE HOADON_MUAHANG
(
	MA_HD ID,
	MA_GH ID,
	MAGIAMGIA ID,
	TT_THANHTOAN CHAR(20),
	TT_GIAOHANG CHAR(20),
	NGAYLAP DATE,
	TOTAL_PRICE MONEY,
	TT_DONHANG CHAR(20)
	CONSTRAINT PK_MA_HD PRIMARY KEY (MA_HD)
)

CREATE TABLE DANHMUC
(
	MA_DM ID NOT NULL,
	TENDM NVARCHAR(100),
	MOTA NVARCHAR(1000),
	CONSTRAINT PK_DM PRIMARY KEY (MA_DM)
)

CREATE TABLE SANPHAM
(
	MA_SP ID NOT NULL, 
	MA_GH ID NOT NULL,
	TENSP NVARCHAR(100),
	GIASP MONEY,  
	SL_CONLAI INT, 
	DANHMUC ID,
	MOTA NVARCHAR(1000)
	CONSTRAINT PK_SANPHAM PRIMARY KEY (MA_SP)
)

CREATE TABLE HOADON
(
	MADONHANG ID NOT NULL,
	MA_GIANHANG ID NOT NULL,	
	MA_KHACHHANG ID,
	NGAYLAP DATETIME DEFAULT(GETDATE()),
	PT_THANHTOAN CHAR(20),
	PT_GIAOHANG CHAR(20),
	DIACHI NVARCHAR(100),
	TRANGTHAI BIT
	CONSTRAINT Pk_HOADON PRIMARY KEY(MADONHANG)
)

CREATE TABLE HOADON_CHITIET
(
	MADONHANG ID NOT NULL,
	MA_SP ID NOT NULL,
	SOLUONG INT,
	DONGIA MONEY, 
	CONSTRAINT PK_HOADONCHITIET PRIMARY KEY (MADONHANG, MA_SP)
)
CREATE TABLE LICHSU_MH
(
	MAKH ID NOT NULL,
	MA_SP ID NOT NULL,
	GIASP MONEY,
	NGAYMUA DATE,
	SOLUONG INT,
	CONSTRAINT PK_LSMUAHANG PRIMARY KEY(MAKH, MA_SP)
)


CREATE TABLE LICHSU_TIMKIEM
(
   	MAKH ID NOT NULL,
        TUKHOA NVARCHAR(100),
        THOIGIAN DATETIME,
)

CREATE TABLE GIAMGIA
(
	MA_GG ID,
	LOAI BIT, --dùng để phân biệt giữa giảm giá khi mua hàng với giảm giá khi bán hàng
	PHANTRAMGIAM INT,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	CONSTRAINT PK_MAGG PRIMARY KEY (MA_GG),
	CONSTRAINT CHECK_PHANTRAMGIAM CHECK (PHANTRAMGIAM BETWEEN 0 AND 100),
	CONSTRAINT CHECK_DATE CHECK (NGAYBATDAU < NGAYKETTHUC)
)

ALTER TABLE KHACH_HANG 
ADD CONSTRAINT FK_KHACHHANG_GIANHANG 
FOREIGN KEY (MA_GIANHANG) REFERENCES GIAN_HANG(MA_GH)

ALTER TABLE KHACH_HANG
ADD CONSTRAINT FK_KHACHHANG_GIOHANG
FOREIGN KEY (MA_GIOHANG) REFERENCES GIOHANG(MA_GH)

ALTER TABLE KHACH_HANG
ADD CONSTRAINT FK_KHACHHANG_TAIKHOAN
FOREIGN KEY (TAIKHOAN) REFERENCES TAIKHOAN(TAIKHOAN)

ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SANPHAN_GIANHANG
FOREIGN KEY (MA_GH) REFERENCES GIAN_HANG(MA_GH)

ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SANPHAM_DANHMUC
FOREIGN KEY(DANHMUC) REFERENCES DANHMUC(MA_DM)

ALTER TABLE GIOHANG_CHITIET
ADD CONSTRAINT FK_GIOHANGCT_MAGH
FOREIGN KEY (MA_GH) REFERENCES GIOHANG(MA_GH)

ALTER TABLE GIOHANG_CHITIET
ADD CONSTRAINT FK_GIOHANGCT_MASP
FOREIGN KEY (MA_SP) REFERENCES SANPHAM(MA_SP)

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_GIANHANG
FOREIGN KEY (MA_GIANHANG) REFERENCES GIAN_HANG(MA_GH)

ALTER TABLE HOADON_CHITIET
ADD CONSTRAINT FK_HOADON_CHITIET_MADH
FOREIGN KEY (MADONHANG) REFERENCES HOADON(MADONHANG)

ALTER TABLE HOADON_CHITIET
ADD CONSTRAINT FK_HOADON_SANPHAM
FOREIGN KEY (MA_SP) REFERENCES SANPHAM(MA_SP)

ALTER TABLE LICHSU_MH
ADD CONSTRAINT FK_LS_KHACHHANG
FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MA_KH)

ALTER TABLE LICHSU_MH
ADD CONSTRAINT FK_LS_SANPHAM 
FOREIGN KEY (MA_SP) REFERENCES SANPHAM(MA_SP)

ALTER TABLE LICHSU_TIMKIEM
ADD CONSTRAINT FK_LSTK_KHACHHANG
FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MA_KH)

ALTER TABLE HOADON_MUAHANG
ADD CONSTRAINT FK_HDMUAHANG
FOREIGN KEY (MA_GH) REFERENCES GIOHANG(MA_GH)

ALTER TABLE HOADON_MUAHANG
ADD CONSTRAINT FK_MAGIAMGIA
FOREIGN KEY (MAGIAMGIA) REFERENCES GIAMGIA(MA_GG)
