USE SALES
GO
--TẠO CHUỖI NGẪU NHIÊN
GO
CREATE VIEW [dbo].[Random]
AS SELECT RAND() AS RAND
GO
CREATE FUNCTION RandomString (@len AS INT)
    RETURNS varchar(MAX)
BEGIN
    DECLARE @STR VARCHAR(8)
    SET @STR = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    DECLARE @newstr VARCHAR(MAX)
    DECLARE @counter int
    SET @newstr = ''
    SET @counter = 0
    WHILE @counter < @len
        BEGIN
            SELECT @newstr = @newstr + SUBSTRING(@str, (SELECT CONVERT(int, (RAND * LEN(@str) + 1)) FROM Random), 1)
            SET @counter = @counter + 1
        END
    RETURN @newstr
END
GO
--chức năng đăng kí tài khoản
GO
CREATE PROCEDURE REGISTER
    @NAME NVARCHAR(50),
    @NGAYSINH DATE,
    @DC NVARCHAR(100),
    @SDT VARCHAR(15),
    @MAIL VARCHAR(50),
    @TK CHAR(8),
    @MK CHAR(8)
AS
BEGIN
    DECLARE
        @MA_GIOHANG ID,
        @MA_KH ID,
        @STATUS INT
    SET @MA_KH = DBO.RandomString(8)
    SET @MA_GIOHANG = DBO.RandomString(8)

    IF EXISTS (SELECT 1 FROM DBO.TAIKHOAN AS TK WHERE TK.TAIKHOAN = @TK)
        BEGIN
            PRINT('TÀI KHOẢN ĐÃ TỒN TẠI')
            SET @STATUS = 0
            RETURN
        END
    IF EXISTS (SELECT 1 FROM DBO.KHACH_HANG AS KH WHERE KH.SODIENTHOAI = @SDT)
        BEGIN
            PRINT('SỐ ĐIỆN THOẠI ĐÃ TỒN TẠI')
            SET @STATUS = 0
            RETURN
        END
    INSERT INTO DBO.TAIKHOAN(TAIKHOAN, MATKHAU) VALUES (@TK, @MK)
    INSERT INTO DBO.GIOHANG VALUES (@MA_GIOHANG, 0, NULL)
    INSERT INTO DBO.KHACH_HANG VALUES (@MA_KH, @NAME, @NGAYSINH, @DC, @SDT, @MAIL, @TK, NULL, @MA_GIOHANG)
    SET @STATUS = 1
END
GO
--CHỨC NĂNG ĐĂNG NHẬP
CREATE PROCEDURE LOG_IN  @MATK AS ID,
                         @MK AS CHAR(8),
                         @STATUS AS INT OUT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM DBO.TAIKHOAN AS TK WHERE TK.TAIKHOAN = @MATK AND TK.MATKHAU = @MK)
        BEGIN
            SET @STATUS = 0
        END
    IF EXISTS (SELECT 1 FROM DBO.TAIKHOAN AS TK WHERE TK.TAIKHOAN = @MATK AND TK.TINHTRANGKICHHOAT =0)
        BEGIN
            SET @STATUS = 2
        END
    SET @STATUS = 1
END
--CHỨC NĂNG TÌM KIẾM
GO
CREATE PROCEDURE SEARCH
    AS
    BEGIN
    SELECT SP.MA_SP, SP.TENSP, SP.GIASP,  SP.SL_CONLAI, SP.DANHMUC, SP.MOTA FROM DBO.SANPHAM AS SP
    END
--TÌM KIẾM THEO TÊN SẢN PHẨM
CREATE PROCEDURE SEARCH_NAME
@NAME NVARCHAR(100)
AS
BEGIN
    SELECT * FROM DBO.SANPHAM AS SP WHERE SP.TENSP LIKE @NAME
END
GO
--TÌM KIẾM THEO TÊN CẢI TIẾN(FULL TEXT INDEX)
--TAO FULLTEX INDEX

CREATE FULLTEXT CATALOG NAME_FULLTEXT_SEARCH

CREATE FULLTEXT INDEX ON DBO.SANPHAM(TENSP)
    KEY INDEX PK_SANPHAM ON NAME_FULLTEXT_SEARCH
    WITH CHANGE_TRACKING AUTO
GO
CREATE PROCEDURE FULLTEXT_INDEX_NAMESEARCH
@NAME NVARCHAR(100)
AS
BEGIN
    SELECT SP.MA_SP, SP.TENSP, SP.GIASP,  SP.SL_CONLAI, SP.DANHMUC, SP.MOTA FROM DBO.SANPHAM AS SP WHERE SP.TENSP LIKE '%'+@NAME+'%'
END
GO
--TÌM KIẾM THEO MÃ SẢN PHẨM
CREATE PROCEDURE SEARCH_ID
@MA_SP NVARCHAR(100)
AS
BEGIN
    SELECT SP.MA_SP, SP.TENSP, SP.GIASP,  SP.SL_CONLAI, SP.DANHMUC, SP.MOTA FROM DBO.SANPHAM AS SP WHERE SP.MA_SP LIKE '%'+@MA_SP+'%'
END
GO
--TẠO INDEX MÃ SẢN PHẨM
CREATE NONCLUSTERED INDEX UNQ_MASP
    ON DBO.SANPHAM(MA_SP)
GO
--TÌM KIẾM THEO DANH MỤC
CREATE PROCEDURE SEARCH_DANHMUC
@MA_DM NVARCHAR(100)
AS
BEGIN
    SELECT SP.MA_SP, SP.TENSP, SP.GIASP,  SP.SL_CONLAI, SP.DANHMUC, SP.MOTA FROM DBO.SANPHAM AS SP WHERE SP.DANHMUC LIKE '%'+@MA_DM+'%'
END
GO
--TẠO INDEX DANH MUC
CREATE NONCLUSTERED INDEX UNQ_DANHMUC
    ON DBO.SANPHAM(DANHMUC)

--CHỨC NĂNG THÊM SẢN PHẨM VÀO GIỎ HÀNG
CREATE PROCEDURE ADD_PRODUCT
    @ID ID,
    @pID ID,
    @SL INT
AS
BEGIN
    DECLARE @FULL_PRICE MONEY
    SET @FULL_PRICE = 0
    DECLARE @PRICE MONEY
    SET @PRICE = 0
    DECLARE @TOTAL MONEY
    SET @TOTAL = 0
    SELECT @PRICE = SP.GIASP  FROM DBO.SANPHAM AS SP WHERE SP.MA_SP = @pID
    INSERT INTO DBO.GIOHANG_CHITIET(MA_GH, MA_SP, SL, DONGIA) VALUES (@ID, @pID, @SL, @PRICE)
    IF(@@rowcount = 1)
        BEGIN
            SET @FULL_PRICE = @PRICE * @SL
            SELECT @TOTAL = GH.TONGTIEN FROM DBO.GIOHANG AS GH WHERE GH.MA_GH = @ID
            SET @TOTAL += @FULL_PRICE
            UPDATE DBO.GIOHANG SET TONGTIEN = @TOTAL WHERE MA_GH = @ID
        END
END
GO
--CHỨC NĂNG TÙY CHỈNH SỐ LƯỢNG TRONG GIỎ HÀNG
CREATE PROCEDURE QTY
    @MA_GH ID,
    @MA_SP ID,
    @QTY INT,
    @PRICE MONEY,
    @STATUS INT OUT
AS
BEGIN
    SET @STATUS = 0
    DECLARE @QTY_OLD INT
    SELECT @QTY_OLD = GHCT.SL FROM DBO.GIOHANG_CHITIET AS GHCT WHERE MA_GH = @MA_GH AND MA_SP = @MA_SP
    IF(@QTY < @QTY_OLD)
        BEGIN
            UPDATE DBO.GIOHANG SET TONGTIEN -= @PRICE*(@QTY_OLD - @QTY) WHERE MA_GH = @MA_GH
            UPDATE DBO.GIOHANG_CHITIET SET SL = @QTY WHERE MA_GH = @MA_GH AND MA_SP = @MA_SP
        END
    ELSE IF(@QTY > @QTY_OLD)
        BEGIN
            UPDATE DBO.GIOHANG SET TONGTIEN += @PRICE*(@QTY - @QTY_OLD) WHERE MA_GH = @MA_GH
            UPDATE DBO.GIOHANG_CHITIET SET SL = @QTY WHERE MA_GH = @MA_GH AND MA_SP = @MA_SP
        END
    IF (@@ROWCOUNT = 1)
        BEGIN
            SET @STATUS = 1
            END
END
GO
--CHỨC NĂNG XÓA SẢN PHẨM KHỎI GIỎ HÀNG
CREATE PROCEDURE DEL_PRODUCT
    @MA_GH ID,
    @MA_SP ID
AS
BEGIN
    DECLARE @PRICE MONEY
    SET @PRICE = 0
    DECLARE @QTY INT
    SET @QTY = 0
    SELECT @PRICE = GH.DONGIA, @QTY = GH.SL FROM DBO.GIOHANG_CHITIET AS GH WHERE GH.MA_GH = @MA_GH AND GH.MA_SP = @MA_SP
    UPDATE DBO.GIOHANG SET TONGTIEN -= @PRICE*@QTY WHERE MA_GH = @MA_GH
    DELETE FROM DBO.GIOHANG_CHITIET WHERE MA_SP = @MA_SP
END
GO
--CHỨC NĂNG XEM SẢN PHẨM TRONG GIỎ HÀNG
CREATE PROCEDURE VIEW_GIOHANG
@MA_GH ID
AS
BEGIN
    SELECT GHCT.MA_SP, GHCT.SL, GHCT.DONGIA FROM DBO.GIOHANG_CHITIET AS GHCT WHERE GHCT.MA_GH = @MA_GH
END
GO
--CHỨC NĂNG THANH TOÁN VÀ LẬP HÓA ĐƠN MUA HÀNG
CREATE PROCEDURE THANHTOAN
    @MA_GH ID,
    @MAGIAMGIA ID,
    @TT_THANHTOAN CHAR(20),
    @TT_GIAOHANG CHAR(20),
    @TOTAL_PRICE MONEY,
    @MA_HD ID OUT
AS
    BEGIN
        SET @MA_HD = DBO.RandomString(8)
        BEGIN
            INSERT INTO DBO.HOADON_MUAHANG VALUES (@MA_HD, @MA_GH, @MAGIAMGIA, @TT_THANHTOAN, @TT_GIAOHANG, GETDATE(),@TOTAL_PRICE, 'APPROVED')
            IF(@@ROWCOUNT = 0)
                BEGIN
                    SET  @MA_HD = 'NULL'
                END
        END
    END
GO
--CHỨC NĂNG KIỂM TRA MÃ GIẢM GIÁ
CREATE PROCEDURE DISCOUNT
    @DISCOUNT_ID ID,
    @DISCOUNT_NUMBER INT OUT
    AS
    BEGIN
        SET @DISCOUNT_NUMBER = 0
        IF EXISTS(SELECT 1 FROM DBO.GIAMGIA AS GG WHERE GG.MA_GG = @DISCOUNT_ID)
            BEGIN
                SELECT @DISCOUNT_NUMBER = GG.PHANTRAMGIAM FROM DBO.GIAMGIA AS GG WHERE GG.MA_GG = @DISCOUNT_ID
                END
        IF NOT EXISTS (SELECT 1 FROM DBO.GIAMGIA AS GG WHERE GETDATE() BETWEEN GG.NGAYBATDAU AND GG.NGAYKETTHUC)
            BEGIN
                SET @DISCOUNT_NUMBER = 0
                END
    END

--CHỨC NĂNG CHUYỂN YÊU CẦU TỪ HÓA ĐƠN SANG NGƯỜI BÁN HÀNG
--SỬ DỤNG CURSOR
  CREATE PROCEDURE SALES_REQUEST
    @MA_GIOHANG ID,
    @PTTT CHAR(20),
    @PTGH CHAR(20),
    @DC CHAR(100),
    @MA_KHACHHANG ID
AS
BEGIN
    DECLARE @HD_ID ID, @MA_SP ID, @SL INT, @MA_GH ID, @DONGIA MONEY
    DECLARE @MA_GIANHANG ID
    DECLARE cusorSales_request CURSOR LOCAL FOR
        SELECT MA_GH, MA_SP, SL, DONGIA FROM DBO.GIOHANG_CHITIET
    OPEN cusorSales_request
    FETCH NEXT FROM cusorSales_request INTO @MA_GIANHANG, @MA_SP, @SL,@DONGIA
    SELECT @MA_GH = GHCT.MA_GH FROM DBO.GIOHANG_CHITIET AS GHCT WHERE GHCT.MA_SP = @MA_SP
    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF(@MA_GH = @MA_GIOHANG)
        BEGIN
            SELECT @MA_GIANHANG = SP.MA_GH FROM DBO.SANPHAM AS SP WHERE SP.MA_SP = @MA_SP
            IF NOT EXISTS(SELECT 1 FROM DBO.HOADON AS HD WHERE HD.MA_GIANHANG = @MA_GIANHANG and HD.NGAYLAP = GETDATE())
            BEGIN
                SET @HD_ID = DBO.RandomString(8)
                INSERT INTO DBO.HOADON(MADONHANG, MA_GIANHANG, MA_KHACHHANG, NGAYLAP, PT_THANHTOAN, PT_GIAOHANG, DIACHI) VALUES (@HD_ID, @MA_GIANHANG, @MA_KHACHHANG, GETDATE(), @PTTT, @PTGH, @DC)
                INSERT INTO DBO.HOADON_CHITIET VALUES (@HD_ID, @MA_SP, @SL, @DONGIA)
            END
            ELSE
                BEGIN
                SELECT @HD_ID = HD.MADONHANG FROM DBO.HOADON AS HD WHERE HD.MA_GIANHANG = @MA_GIANHANG
                INSERT INTO DBO.HOADON_CHITIET VALUES (@HD_ID, @MA_SP, @SL, @DONGIA)
            END
        END
        INSERT INTO LICHSU_MH VALUES (@MA_KHACHHANG, @MA_SP, @DONGIA, GETDATE(), @SL)
        FETCH NEXT FROM cusorSales_request INTO @MA_GH, @MA_SP, @SL, @DONGIA
        SELECT @MA_GH = GHCT.MA_GH FROM DBO.GIOHANG_CHITIET AS GHCT WHERE GHCT.MA_SP = @MA_SP
SELECT * FROM DBO.LICHSU_MH
    END
        CLOSE cusorSales_request
        DEALLOCATE cusorSales_request
    END
GO
------------CHỨC NĂNG NGƯỜI BÁN HÀNG-------------------
--CHỨC NĂNG ĐĂNG KÍ GIAN HÀNG
CREATE PROCEDURE SALES_REGISTER
    @KH_TK ID,
    @SO_DIENTHOAI  VARCHAR(15),
    @EMAIL VARCHAR(50),
    @STATUS INT OUT
AS
BEGIN
    DECLARE @MAGIANHANG ID
    SET @MAGIANHANG = DBO.RandomString(8)
    SET @STATUS = 0
    INSERT INTO DBO.GIAN_HANG VALUES (@MAGIANHANG, @SO_DIENTHOAI, @EMAIL, GETDATE(), 5)
    IF(@@ROWCOUNT = 1)
        BEGIN
            SET @STATUS = 1
            UPDATE DBO.KHACH_HANG SET MA_GIANHANG = @MAGIANHANG WHERE TAIKHOAN = @KH_TK
            END
END
GO
--CHỨC NĂNG ĐĂNG KÍ SẢN PHẨM ĐỂ BÁN
CREATE PROCEDURE PRODUCT_REGISTER
    @GH_ID ID,
    @TENSP NVARCHAR(100),
    @GIASP MONEY,
    @SLCONLAI INT,
    @DANHMUC ID,
    @MOTA NVARCHAR(1000),
    @STATUS INT OUT
AS
BEGIN
    SET @STATUS = 0
    DECLARE @MA_SP ID
    SET @MA_SP = DBO.RandomString(8)
    INSERT INTO DBO.[SANPHAM](MA_SP, MA_GH, TENSP, GIASP, SL_CONLAI, DANHMUC, MOTA) VALUES (@MA_SP, @GH_ID, @TENSP, @GIASP, @SLCONLAI, @DANHMUC, @MOTA)
    IF(@@ROWCOUNT = 1)
    BEGIN SET @STATUS = 1
      END
END
    DROP PROCEDURE PRODUCT_REGISTER
    GO
--CHỨC NĂNG XÓA SẢN PHẨM TRÊN GIAN HÀNG
CREATE PROCEDURE DELETE_PRODUCT
@PRODUCTID ID
AS
BEGIN
    DELETE FROM DBO.SANPHAM WHERE @PRODUCTID = MA_SP
END
GO
--CHỨC NĂNG CẬP NHẬT TRẠNG THÁI GIAO HÀNG
CREATE PROCEDURE UPDATE_ORDER
    @HDMHID ID,
    @TTDH CHAR(20)
AS
BEGIN
    UPDATE DBO.HOADON_MUAHANG SET TT_DONHANG = @TTDH WHERE MA_HD = @HDMHID
END
GO
--CHỨC NĂNG KHÓA TÀI KHOẢN
CREATE PROCEDURE BLOCK_ACCOUNT
@TK char(8)
AS
BEGIN
    UPDATE DBO.TAIKHOAN SET TINHTRANGKICHHOAT = 0 WHERE TAIKHOAN = @TK
END
--CHỨC NĂNG LẤY TÊN KHÁCH HÀNG
    CREATE PROCEDURE GET_TENKH
        @MA_TK ID,
        @TEN_KH NVARCHAR(50) OUT
    AS
    BEGIN
        SELECT @TEN_KH = KH.TEN_KH FROM DBO.KHACH_HANG AS KH WHERE KH.TAIKHOAN = @MA_TK
    END
--CHỨC NĂNG XÁC NHẬN ĐƠN HÀNG
CREATE PROCEDURE APPROVED
    @MADONHANG ID
    AS
    BEGIN
        UPDATE DBO.HOADON SET TRANGTHAI = 1 WHERE MADONHANG = @MADONHANG
    END
--CHỨC NĂNG LẤY MÃ KHÁCH HÀNG
CREATE PROCEDURE GET_MAKH
@MA_TK ID,
@MA_KH ID OUT
AS
    BEGIN
        SELECT @MA_KH = KH.MA_KH FROM DBO.KHACH_HANG AS KH WHERE KH.TAIKHOAN = @MA_TK
    END
--CHỨC NĂNG LẤY MÃ GIỎ HÀNG
CREATE PROCEDURE GET_MAGIOHANG
@MA_TK ID,
@MA_GIOHANG ID OUT
AS
BEGIN
    SELECT @MA_GIOHANG = KH.MA_GIOHANG
    FROM DBO.KHACH_HANG AS KH WHERE KH.TAIKHOAN = @MA_TK
END
--CHỨC NĂNG LẤY MÃ GIAN HÀNG
CREATE PROCEDURE MA_GIANHANG
    @ID ID,
    @MAGIANHANG ID OUT
    AS BEGIN
        SELECT @MAGIANHANG = KH.MA_GIANHANG FROM DBO.KHACH_HANG AS KH WHERE KH.TAIKHOAN = @ID
        END
--CHỨC NĂNG LẤY MÃ ĐƠN HÀNG
CREATE PROCEDURE MA_DONHANG
    @MA_GIANHANG ID,
    @MA_DONHANG ID OUT
    AS
    BEGIN
        SELECT @MA_DONHANG = HD.MADONHANG FROM DBO.HOADON AS HD WHERE HD.MA_GIANHANG = @MA_GIANHANG
    end
--CHỨC NĂNG LẤY TỔNG TIỀN CỦA ĐƠN HÀNG
CREATE PROCEDURE TOTAL_MONEY
    @MA_GIOHANG NVARCHAR(100),
    @TONGTIEN MONEY OUT
AS
    BEGIN
        SELECT  @TONGTIEN = GH.TONGTIEN FROM DBO.GIOHANG AS GH WHERE GH.MA_GH = @MA_GIOHANG
    end

ALTER TABLE GIOHANG WITH NOCHECK
ADD CONSTRAINT CK_GIOHANG CHECK (TONGTIEN IS NOT NULL AND TONGTIEN >= 0)

select * from dbo.TAIKHOAN
--KIỂM TRA ĐÃ CÓ SHOP HAY CHƯA
CREATE PROCEDURE CHECKSHOP
    @MA_KH ID,
    @STATUS INT OUT
    AS
    BEGIN
        SET @STATUS =0
        IF EXISTS(SELECT 1 FROM DBO.KHACH_HANG AS KH WHERE KH.TAIKHOAN = @MA_KH AND KH.MA_GIANHANG IS NOT NULL)
        BEGIN
            SET @STATUS = 1
        end
    end
--CHỨC NĂNG CỬA HÀNG XEM CÁC SẢN PHẨM ĐANG ĐƯỢC BÁN
CREATE PROCEDURE MYSHOP
    @MA_GIANHANG ID
    AS
    BEGIN
        SELECT SP.MA_SP, SP.TENSP, SP.GIASP,  SP.SL_CONLAI, SP.DANHMUC, SP.MOTA FROM DBO.SANPHAM AS SP WHERE SP.MA_GH = @MA_GIANHANG
        END
--CHỨC NĂNG XÓA HẾT SẢN PHẨM CỦA GIỎ HÀNG SAU KHI THANH TOÁN
CREATE PROCEDURE DEL_ALLPRODUCT
    @MA_GH ID
    AS
    BEGIN
        UPDATE DBO.GIOHANG SET TONGTIEN =0 WHERE MA_GH = @MA_GH
        DELETE FROM DBO.GIOHANG_CHITIET WHERE MA_GH = @MA_GH
    END
--CHỨC NĂNG GIAN HÀNG XEM CÁC ĐƠN ĐẶT HÀNG
CREATE PROCEDURE MY_ORDER
    @MAGIANHANG ID
    AS
    BEGIN
        SELECT HD.MADONHANG, HD.MA_KHACHHANG, HD.NGAYLAP, HD.PT_THANHTOAN, HD.PT_GIAOHANG, DIACHI FROM DBO.HOADON AS HD WHERE HD.MA_GIANHANG = @MAGIANHANG AND HD.TRANGTHAI = 0
    END
--CHỨC NĂNG XEM HÓA ĐƠN CHI TIẾT
CREATE PROCEDURE DETAILS_ORDER
    @MA_DH ID
    AS
    BEGIN
        SELECT MADONHANG,MA_SP, SOLUONG, DONGIA FROM DBO.HOADON_CHITIET AS HDCT WHERE HDCT.MADONHANG = @MA_DH
    END
--CHỨC NĂNG XEM LỊCH SỬ MUA HÀNG
CREATE PROCEDURE PURCHASE_HISTORY
    @MA_KH ID
    AS
    BEGIN
        SELECT LSMH.MA_SP, LSMH.GIASP, LSMH.NGAYMUA, LSMH.SOLUONG FROM DBO.LICHSU_MH AS LSMH WHERE LSMH.MAKH = @MA_KH
    END
--CHỨC NĂNG THÊM LỊCH SỬ TÌM KIẾM
CREATE PROCEDURE SEARCH_HISTORY
    @MA_KH ID,
    @TUKHOA NVARCHAR(100),
    @DANHMUC VARCHAR(50)
    AS
    BEGIN
        INSERT INTO DBO.LICHSU_TIMKIEM VALUES (@MA_KH, @TUKHOA, GETDATE(), @DANHMUC)
    END
--CHỨC NĂNG XEM LỊCH SỬ TÌM KIẾM
CREATE PROCEDURE SHOW_SEARCH_HISTORY
    @MA_KH ID
    AS
    BEGIN
        SELECT LSTK.TUKHOA, LSTK.THOIGIAN, LSTK.DANHMUC FROM DBO.LICHSU_TIMKIEM AS LSTK WHERE LSTK.MAKH = @MA_KH
        END
-----------